[project]
name = "telegram-printer-bot"
version = "0.1.0"
description = "A Telegram bot for printing documents and images using a local printer."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-telegram-bot>=22.1",
    "python-dotenv>=1.1.0",
]